### ISSUE TITLE
First time use error...

### ISSUE THREAD

**Issue by stevenjstromer** [MStadlmeier/drivesync#31]
Installed drivesync on osx, after installing Ruby 2.6.x using homebrew. I understand that I need to create the config.yml file by running drivesync.rb, but when I do, I get the following. Any possible guidance? Thanks!

```
ruby drivesync.rb
Traceback (most recent call last):
	4: from drivesync.rb:1:in `<main>'
	3: from drivesync.rb:1:in `require_relative'
	2: from /Users/sstromer/Applications/GitHub/drivesync/src/synchronizer.rb:1:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- google/apis/drive_v3 (LoadError)

```

**Comment by MStadlmeier** [comment]
Ruby can't find the Google Drive API. Did you run  `bundle install` before starting drivesync?

**Comment by stevenjstromer** [comment]
I ran the following, before getting the error:
`bundle install --path vendor/bundle`

I assume this was incorrect, and that's why it isn't locating the api. Possible to steer me in the correct direction?

**Comment by stevenjstromer** [comment]
Still hoping I can get some pro guidance on this. Did I install the bundle to the wrong location? Thanks for any assist.

**Comment by MStadlmeier** [comment]
Are you getting the same problem when you just run bundle install without any arguments?
