### ISSUE TITLE
Crash during Suspend/Resume cycle

### ISSUE THREAD

**Issue by axet** [MStadlmeier/drivesync#37]
Hello!

Here is a crash during initial sync with syspend resume.

```
Downloading file .encfs/NmrQM-ZiuEslkdRee437XXTB/J-K6K3ee9gtpdjA4n1nbzJkRRTEqxCcQWoqBotn4FXTHN,/i805m1NMpytudSkYE2QMAaloaLFKnfK9NKCjaJPyWNekF-/Lg0Rzs858ZPG2DKke7BKdl6J/c-qluFY6bppY3l7bTqK9qnpy/HpbXdxf0QF1gAyBtEY1ySmSo/YHstEBlucUbgxM-UdgaZj6gjX2G-E7upS3CxI3yflUImTuqBDLueHKh0UkE9denuln8 ...
Traceback (most recent call last):
	36: from /home/axet/local/drivesync/drivesync.rb:64:in `<main>'
	35: from /home/axet/local/drivesync/drivesync.rb:23:in `sync'
	34: from /home/axet/local/drivesync/src/synchronizer.rb:71:in `run'
	33: from /home/axet/local/drivesync/src/synchronizer.rb:267:in `sync'
	32: from /home/axet/local/drivesync/src/synchronizer.rb:267:in `each'
	31: from /home/axet/local/drivesync/src/synchronizer.rb:270:in `block in sync'
	30: from /home/axet/local/drivesync/src/synchronizer.rb:151:in `download_file'
	29: from /home/axet/local/drivesync/src/drive_manager.rb:99:in `download'
	28: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/generated/google/apis/drive_v3/service.rb:792:in `get_file'
	27: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	26: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:93:in `execute'
	25: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	24: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	23: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	22: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:101:in `block in execute'
	21: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	20: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	19: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	18: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	17: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/download.rb:77:in `execute_once'
	16: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:743:in `get'
	15: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
	14: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
	13: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	12: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	11: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	10: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'
	 9: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'
	 8: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'
	 7: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'
	 6: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'
	 5: from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
	 4: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `block in parse_header'
	 3: from /var/lib/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:62:in `gets'
	 2: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:207:in `gets'
	 1: from /usr/lib/ruby/2.5.0/openssl/buffering.rb:57:in `fill_rbuff'
/usr/lib/ruby/2.5.0/openssl/buffering.rb:57:in `sysread': execution expired (Google::Apis::TransmissionError)
```

**Comment by MStadlmeier** [comment]
This seems to be an issue with the Drive API or an even lower layer. It might have something to do with the gigantic filename/path or the file itself. How large is the file that is being downloaded (at the top of the log file)?
