### ISSUE TITLE
Error when trying to run it for the first time

### ISSUE THREAD

**Issue by cesarhndz** [MStadlmeier/drivesync#41]
Hello, does anyone know how to fix this issue?, thanks in advance

cesar@cesar-HP-Compaq-Pro-6300-SFF:~/drivesync$ ruby drivesync.rb
Local folder is 168 files behind and 73 files ahead of remote
Traceback (most recent call last):
	5: from drivesync.rb:64:in `<main>'
	4: from drivesync.rb:23:in `sync'
	3: from /home/cesar/drivesync/src/synchronizer.rb:68:in `run'
	2: from /home/cesar/drivesync/src/synchronizer.rb:224:in `load_manifest'
	1: from /usr/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '' (JSON::ParserError)

**Comment by MStadlmeier** [comment]
Hi, @cesarhndz , sorry for the late reply.
Looks like there may be something wrong with your manifest file. Have you tried resetting drivesync with `rb drivesync.rb reset` ? This will delete the manifest and should resolve any errors related to it. Make sure to backup your local drive folder first if you have any pending changes there.
