### ISSUE TITLE
Server error when uploading thousends of small files

### ISSUE THREAD

**Issue by Mustafa-MS** [MStadlmeier/drivesync#47]
Hi, I'm using drivesync to upload (~750000) file to my google drive, but every hundreds file the app stops with an error.
each file is about 160 KB only, my google drive have a large empty space more than what I need.
I'm using Ubuntu 20.04.02

> Uploading file project/cropped_nodules/358094.npy ...
Traceback (most recent call last):
	23: from drivesync.rb:64:in `<main>'
	22: from drivesync.rb:23:in `sync'
	21: from /home/mustafa/drivesync/src/synchronizer.rb:71:in `run'
	20: from /home/mustafa/drivesync/src/synchronizer.rb:279:in `sync'
	19: from /home/mustafa/drivesync/src/synchronizer.rb:279:in `each'
	18: from /home/mustafa/drivesync/src/synchronizer.rb:282:in `block in sync'
	17: from /home/mustafa/drivesync/src/synchronizer.rb:166:in `upload_file'
	16: from /home/mustafa/drivesync/src/drive_manager.rb:116:in `upload'
	15: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/generated/google/apis/drive_v3/service.rb:601:in `create_file'
	14: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	13: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:93:in `execute'
	12: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	11: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	10: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 9: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:101:in `block in execute'
	 8: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	 7: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 6: from /var/lib/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 5: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:104:in `block (2 levels) in execute'
	 4: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/upload.rb:246:in `execute_once'
	 3: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/upload.rb:170:in `process_response'
	 2: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:183:in `process_response'
	 1: from /var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/api_command.rb:118:in `check_status'
/var/lib/gems/2.5.0/gems/google-api-client-0.23.4/lib/google/apis/core/http_command.rb:221:in `check_status': Server error (Google::Apis::ServerError)

**Comment by Mustafa-MS** [comment]
after few tries now the whole app is not working!
