### ISSUE TITLE
Drivesync stopped working : "cannot load such file -- google/apis/drive_v3 (LoadError)"

### ISSUE THREAD

**Issue by Tromzy** [MStadlmeier/drivesync#48]
Hi,

I use drivesync on two different machines, both running Archlinux, and recently they both got this error when launching ruby drivesync.rb (both used to work perfectly fine before) : 

ruby drivesync/drivesync.rb                                             ✔  14:46:34  
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- google/apis/drive_v3 (LoadError)
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/tromzy/drivesync/src/synchronizer.rb:1:in `<top (required)>'
        from drivesync/drivesync.rb:1:in `require_relative'
        from drivesync/drivesync.rb:1:in `<main>'

What should I do ?

**Comment by Tromzy** [comment]
I found the solution, I had to downgrade ruby and rubygems to previous versions (ruby 3.0 -> 2.7 and rubygems 3.2.15 -> 3.2.13).
