### ISSUE TITLE
Uninstall Drivesync

### ISSUE THREAD

**Issue by vinagre77** [MStadlmeier/drivesync#51]
Hi.
I have problems with Drivesync and I would like to uninstall it to install it again. How can I do it?
Thanks.

**Comment by vinagre77** [comment]
I work in Ubuntu 22.04

**Comment by vinagre77** [comment]
Actually, my problem is that, when I write "bundle install", it appears an error:
"google-api-client-0.23.4 requires ruby version 2.0, wich is incompatible with the current version, ruby 3.0.2p107".

**Comment by vinagre77** [comment]
And when I write "ruby drivesync.rb", it says:
"drivesync.rb:1:in `require_relative`: /root/drivesync/src/synchronizer.rb:130: syntax error, unexpected keyword_do_block, expecting keyword_end (SyntaxError)
@drive.files.each do (file)
/root/drivesync/src/synchronizer.rb:330: syntax error, unexpected keyword_end, expecting end-of-input
from drivesync.rb:1:in `main"
