### ISSUE TITLE
Error uploading files

### ISSUE THREAD

**Issue by jaliprandi** [MStadlmeier/drivesync#53]
This has been working flawlessly for months (thank you). Did Google change their API or something?

```
Uploading file Classroom/Physical Science 10 Spring 2023/notes/7D Periodic Trends.pdf ...
/home/xxx/software/drivesync/src/drive_manager.rb:158:in `block in folder_with_name': undefined method `first' for nil:NilClass (NoMethodError)
        from /home/xxx/software/drivesync/src/drive_manager.rb:158:in `select'
        from /home/xxx/software/drivesync/src/drive_manager.rb:158:in `folder_with_name'
        from /home/xxx/software/drivesync/src/drive_manager.rb:180:in `block in traverse_and_create'
        from /home/xxx/software/drivesync/src/drive_manager.rb:178:in `each'
        from /home/xxx/software/drivesync/src/drive_manager.rb:178:in `traverse_and_create'
        from /home/xxx/software/drivesync/src/drive_manager.rb:108:in `upload'
        from /home/xxx/software/drivesync/src/synchronizer.rb:166:in `upload_file'
        from /home/xxx/software/drivesync/src/synchronizer.rb:282:in `block in sync'
        from /home/xxx/software/drivesync/src/synchronizer.rb:279:in `each'
        from /home/xxx/software/drivesync/src/synchronizer.rb:279:in `sync'
        from /home/xxx/software/drivesync/src/synchronizer.rb:71:in `run'
        from drivesync.rb:23:in `sync'
        from drivesync.rb:64:in `<main>'
```

**Comment by jaliprandi** [comment]
Is it possible spaces aren't playing well in file/folder names? They had been working, but I manually synced some files, and then the rest were able to be automatically synced.
There's two things that might differentiate the errors from the successes.
- The files that were in error had spaces in their names, and the files that succeeded had no spaces
- The files that were in error have their local containing folders bound to other folders on my machine using fstab. I can't imagine why this would matter, because they sync from the physical location, not the bound one.
